verbose: true
instrumentation:
    root: .
    default-excludes: true
    excludes: [
    'public/bower-components/**/*.js',
    'public/**/*.js',
    'modules/**/*.js',
    'app/**/views/**/*.js',
    'app/config/**/*.js',
    'gulp-tasks/**/*.js',
    'test/**/*.js']
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
reporting:
    print: summary
    reports:
        - html
    dir: ./test/coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
hooks:
    hook-run-in-context: false
    post-require-hook: null
